### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ciukstar** [shogogg/ts-option#19]
Failed to compile with `ts-option@2.1.0`
```
Failed to compile.

../node_modules/ts-option/index.d.ts:137:9 - error TS1086: An accessor cannot be declared in an ambient context.

137     get get(): A;
            ~~~
../node_modules/ts-option/index.d.ts:140:9 - error TS1086: An accessor cannot be declared in an ambient context.

140     get isDefined(): boolean;
            ~~~~~~~~~
../node_modules/ts-option/index.d.ts:141:9 - error TS1086: An accessor cannot be declared in an ambient context.

141     get isEmpty(): boolean;
            ~~~~~~~
../node_modules/ts-option/index.d.ts:144:9 - error TS1086: An accessor cannot be declared in an ambient context.

144     get nonEmpty(): boolean;
            ~~~~~~~~
../node_modules/ts-option/index.d.ts:147:9 - error TS1086: An accessor cannot be declared in an ambient context.

147     get orNull(): A | null;
            ~~~~~~
../node_modules/ts-option/index.d.ts:148:9 - error TS1086: An accessor cannot be declared in an ambient context.

148     get orUndefined(): A | undefined;
            ~~~~~~~~~~~
../node_modules/ts-option/index.d.ts:149:9 - error TS1086: An accessor cannot be declared in an ambient context.

149     get toArray(): A[];
            ~~~~~~~
../node_modules/ts-option/index.d.ts:161:9 - error TS1086: An accessor cannot be declared in an ambient context.

161     get get(): A;
            ~~~
../node_modules/ts-option/index.d.ts:164:9 - error TS1086: An accessor cannot be declared in an ambient context.

164     get isDefined(): boolean;
            ~~~~~~~~~
../node_modules/ts-option/index.d.ts:165:9 - error TS1086: An accessor cannot be declared in an ambient context.

165     get isEmpty(): boolean;
            ~~~~~~~
../node_modules/ts-option/index.d.ts:168:9 - error TS1086: An accessor cannot be declared in an ambient context.

168     get nonEmpty(): boolean;
            ~~~~~~~~
../node_modules/ts-option/index.d.ts:171:9 - error TS1086: An accessor cannot be declared in an ambient context.

171     get orNull(): A | null;
            ~~~~~~
../node_modules/ts-option/index.d.ts:172:9 - error TS1086: An accessor cannot be declared in an ambient context.

172     get orUndefined(): A | undefined;
            ~~~~~~~~~~~
../node_modules/ts-option/index.d.ts:173:9 - error TS1086: An accessor cannot be declared in an ambient context.

173     get toArray(): Array<A>;
            ~~~~~~~
```
Env:
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.18
Node: 10.16.0
OS: linux x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.18
@angular-devkit/build-angular     0.803.18
@angular-devkit/build-optimizer   0.803.18
@angular-devkit/build-webpack     0.803.18
@angular-devkit/core              8.3.18
@angular-devkit/schematics        8.3.18
@angular/cdk                      8.2.3
@angular/cli                      8.3.18
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.18
@schematics/angular               8.3.18
@schematics/update                0.803.18
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```
